### ISSUE TITLE
Instructions say to enter date in past, pre-existing SN code disallows this.

### ISSUE THREAD

**Issue by Muzical84** [ServiceNow/devtraining-needit-paris#126]
I'd been working on the New to ServiceNow path on Orlando, but eventually we were going to upgrade to Paris.  I upgraded my instance, wiped the data, and forked this repo, imported, all that good stuff.  However, and I had this issue with Notifications on the Orlando version of the repo, too, when I try and do as https://developer.servicenow.com/dev.do#!/learn/learning-plans/paris/new_to_servicenow/app_store_learnv2_automatingapps_paris_exercise_use_application_property instructs, I cannot actually save anything, even after checking out exactly the tag required for this training module, because I'm not allowed to save this date in the past.

Now, that's a problem I know enough to fix, but it tells me QA didn't verify this process, and if I was JUST relying on the learning path for ALL of my SN knowledge and experience, I would currently be packing 😅

**Comment by bsweets** [comment]
Hi Janet,

In the future, can you please submit feedback from the bottom of the learning page instead of through GitHub? We track feedback and reported issues that way.

As for your issue, it sounds like you are working with a _NeedIt_ record. You should be working with a _NeedIt Task_ record for the exercise. _NeedIt Task_ records allow you to enter a date in the past. You should not need to rely on all your SN knowledge and experience to complete the exercise. :D 

Happy developing,
Ben Sweetser
ServiceNow Developer Program
